modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sizer"
version="1.0.0"
displayName="Sizer"
authors="TastyPommesLul"
description="Allows resizing players."

[[dependencies.sizer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.sizer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
